https://www.guru99.com/tensor-tensorflow.html

# What is a Tensor?
A tensor is a vector or matrix of n-dimensions that represents all types of data. All values in a tensor hold identical data type with a known (or partially known) shape. The shape of the data is the dimensionality of the matrix or array.


In TensorFlow, all the operations are conducted inside a graph. The graph is a set of computation that takes place successively. Each operation is called an **op node** and are connected to each other.

In Machine Learning, models are feed with a list of objects called **feature vectors*\*.

 These values will flow into an op node through the tensor and the result of this operation/computation will create a new tensor which in turn will be used in a new operation. All these operations can be viewed in the graph.
 
 

Representation of a Tensor
In TensorFlow, a tensor is a collection of feature vectors (i.e., array) of n-dimensions. For instance, if we have a 2x3 matrix with values from 1 to 6, we write:



TensorFlow represents this matrix as:

In [22]:
[[1, 2, 3],
 [4, 5, 6]
]

[[1, 2, 3], [4, 5, 6]]

## Types of Tensor
In TensorFlow, all the computations pass through one or more tensors. A tensor is an object with three properties:

A unique label (name)
A dimension (shape)
A data type (dtype)
Each operation you will do with TensorFlow involves the manipulation of a tensor. There are four main tensors you can create:

1. tf.Variable
2. tf.constant
3. tf.placeholder
4. tf.SparseTensor

## Create a tensor of n-dimension

In [23]:
import tensorflow as tf

To create a tensor of dimension 0, run the following code

In [24]:
## rank 0
# Default name
r1 = tf.constant(1, tf.int16) 
print(r1)

Tensor("Const_19:0", shape=(), dtype=int16)


In [25]:
# Decimal
r1_decimal = tf.constant(1.12345, tf.float32)
print(r1_decimal)
# String
r1_string = tf.constant("Guru99", tf.string)
print(r1_string)

Tensor("Const_20:0", shape=(), dtype=float32)
Tensor("Const_21:0", shape=(), dtype=string)


A tensor of dimension 1 can be created as follow:

In [26]:
## Rank 1
r1_vector = tf.constant([1,3,5], tf.int16)
print(r1_vector)
r2_boolean = tf.constant([True, True, False], tf.bool)
print(r2_boolean)

Tensor("Const_22:0", shape=(3,), dtype=int16)
Tensor("Const_23:0", shape=(3,), dtype=bool)


To create an array of 2 dimensions, you need to close the brackets after each row. Check the examples below

In [27]:
## Rank 2
r2_matrix = tf.constant([ [1, 2],
                          [3, 4] ],tf.int16)
print(r2_matrix)

Tensor("Const_24:0", shape=(2, 2), dtype=int16)


A matrix with 3 dimensions is constructed by adding another level with the brackets.

In [28]:
## Rank 3
r3_matrix = tf.constant([ [[1, 2],
                           [3, 4], 
                           [5, 6]] ], tf.int16)
print(r3_matrix)

Tensor("Const_25:0", shape=(1, 3, 2), dtype=int16)


Shape of tensor
When you print the tensor, TensorFlow guesses the shape. However, you can get the shape of the tensor with the shape property.

Below, you construct a matrix filled with a number from 10 to 15 and you check the shape of m_shape

In [29]:
# Shape of tensor
m_shape = tf.constant([ [10, 11],
                        [12, 13],
                        [14, 15] ]                      
                     ) 
m_shape.shape

TensorShape([Dimension(3), Dimension(2)])

In [30]:
# Create a vector of 0
print(tf.zeros(10))

Tensor("zeros_1:0", shape=(10,), dtype=float32)


In [31]:
# Create a vector of 1
print(tf.ones([10, 10]))

Tensor("ones_1:0", shape=(10, 10), dtype=float32)


tf.add(a, b)
tf.substract(a, b)
tf.multiply(a, b)
tf.div(a, b)
tf.pow(a, b)
tf.exp(a)
tf.sqrt(a)

In [32]:
# Add
tensor_a = tf.constant([[1,2]], dtype = tf.int32)
tensor_b = tf.constant([[3, 4]], dtype = tf.int32)

# Multiply
tensor_multiply = tf.multiply(tensor_a, tensor_b)
print(tensor_multiply)	

Tensor("Mul_1:0", shape=(1, 2), dtype=int32)


## Placeholder
A placeholder has the purpose of feeding the tensor. Placeholder is used to initialize the data to flow inside the tensors. To supply a placeholder, you need to use the method feed_dict. The placeholder will be fed only within a session.

Session
TensorFlow works around 3 main components:

Graph
Tensor
Session

## Graph

The graph is fundamental in TensorFlow. All of the mathematical operations (ops) are performed inside a graph. You can imagine a graph as a project where every operations are done. The nodes represent these ops, they can absorb or create new tensors.

## Tensor

A tensor represents the data that progress between operations. You saw previously how to initialize a tensor. The difference between a constant and variable is the initial values of a variable will change over time.

## Session

A session will execute the operation from the graph. To feed the graph with the values of a tensor, you need to open a session. Inside a session, you must run an operator to create an output.

Graphs and sessions are independent. You can run a session and get the values to use later for further computations.

In the example below, you will:

Create two tensors
Create an operation
Open a session
Print the result
Step 1) You create two tensors x and y

## Create, run  and evaluate a session

In [33]:
x = tf.constant([2])
y = tf.constant([4])

		
Step 2) You create the operator by multiplying x and y

## Create operator

In [34]:
multiply = tf.multiply(x, y)		

	
Step 3) You open a session. All the computations will happen within the session. When you are done, you need to close the session.

## Create a session to run the code

In [36]:
sess = tf.Session()
result_1 = sess.run(multiply)
print(result_1)
sess.close()

[8]


Output

[8]			
Code explanation

tf.Session(): Open a session. All the operations will flow within the sessions
run(multiply): execute the operation created in step 2.
print(result_1): Finally, you can print the result
close(): Close the session
The result shows 8, which is the multiplication of x and y.

Another way to create a session is inside a block. The advantage is it automatically closes the session.

In [38]:
with tf.Session() as sess:    
    result_2 = multiply.eval()
print(result_2) 			

[8]


Output

[8]			
In a context of the session, you can use the eval() method to execute the operation. It is equivalent to run(). It makes the code more readable.

You can create a session and see the values inside the tensors you created so far.

## Check the tensors created before

In [39]:
sess = tf.Session()
print(sess.run(r1))
print(sess.run(r2_matrix))
print(sess.run(r3_matrix))			

1
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]
  [5 6]]]


Output

1
[[1 2] 
 [3 4]]
[[[1 2]  
  [3 4]  
  [5 6]]]			
Variables are empty by default, even after you create a tensor. You need to initialize the variable if you want to use the variable. The object tf.global_variables_initializer() needs to be called to initialize the values of a variable. This object will explicitly initialize all the variables. This is helpful before you train a model.

You can check the values of the variables you created before. Note that you need to use run to evaluate the tensor

In [42]:
sess.run(tf.global_variables_initializer())
#print(sess.run(var))
print(sess.run(var_init_1))
print(sess.run(var_init_2))

NameError: name 'var_init_1' is not defined

Output

[[-0.05356491  0.75867283]]
[[0 0]]
[[10 20] 
 [30 40]]			
You can use the placeholder you created before and feed it with actual value. You need to pass the data into the method feed_dict.

For example, you will take the power of 2 of the placeholder data_placeholder_a.

import numpy as np
power_a = tf.pow(data_placeholder_a, 2)
with tf.Session() as sess:  
data = np.random.rand(1, 10)  
print(sess.run(power_a, feed_dict={data_placeholder_a: data}))  # Will succeed.			
Code Explanation

import numpy as np: Import numpy library to create the data
tf.pow(data_placeholder_a, 2): Create the ops
np.random.rand(1, 10): Create a random array of data
feed_dict={data_placeholder_a: data}: Feed the placeholder with data
Output

[[0.05478134 0.27213147 0.8803037  0.0398424  0.21172127 0.01444725  0.02584014 0.3763949  0.66022706 0.7565559 ]]			
Graph
TensorFlow depends on a genius approach to render the operation. All the computations are represented with a dataflow scheme. The dataflow graph has been developed to see to data dependencies between individual operation. Mathematical formula or algorithm are made of a number of successive operations. A graph is a convenient way to visualize how the computations are coordinated.

The graph shows a node and an edge. The node is the representation of a operation, i.e. the unit of computation. The edge is the tensor, it can produce a new tensor or consume the input data. It depends on the dependencies between individual operation.

The structure of the graph connects together the operations (i.e. the nodes) and how those are operation are feed. Note that the graph does not display the output of the operations, it only helps to visualize the connection between individual operations.

Let's see an example.

Imagine you want to evaluate the following function:



TensorFlow will create a graph to execute the function. The graph looks like this:



You can easily see the path that the tensors will take to reach the final destination.

For instance, you can see the operation add cannot be done before and . The graph explains that it will:

compute and :
add 1) together
add to 2)
add 3) to
x = tf.get_variable("x", dtype=tf.int32,  initializer=tf.constant([5]))
z = tf.get_variable("z", dtype=tf.int32,  initializer=tf.constant([6]))
c = tf.constant([5], name =	"constant")square = tf.constant([2], name =	"square")
f = tf.multiply(x, z) + tf.pow(x, square) + z + c			
Code Explanation

x: Initialize a variable called x with a constant value of 5
z: Initialize a variable called z with a constant value of 6
c: Initialize a constant tensor called c with a constant value of 5
square: Initialize a constant tensor called square with a constant value of 2
f: Construct the operator
In this example, we choose to keep the values of the variables fixed. We also created a constant tensor called c which is the constant parameter in the function f. It takes a fixed value of 5. In the graph, you can see this parameter in the tensor called constant.

We also constructed a constant tensor for the power in the operator tf.pow(). It is not necessary. We did it so that you can see the name of the tensor in the graph. It is the circle called square.

From the graph, you can understand what will happen of the tensors and how it can return an output of 66.

The code below evaluate the function in a session.

init = tf.global_variables_initializer() # prepare to initialize all variables
with tf.Session() as sess:    
	init.run() # Initialize x and y    
    function_result = f.eval()
print(function_result)    			
Output

[66]			
Summary
TensorFlow works around:

Graph: Computational environment containing the operations and tensors
Tensors: Represents the data (or value) that will flow in the graph. It is the edge in the graph
Sessions: Allow the execution of the operations
Create a constant tensor

constant

object

D0

tf.constant(1, tf.int16)

D1

tf.constant([1,3,5], tf.int16)

D2

tf.constant([ [1, 2], [3, 4] ],tf.int16)

D3

tf.constant([ [[1, 2],[3, 4], [5, 6]] ], tf.int16)

Create an operator

Create an operator

Object

a+b

tf.add(a, b)

a*b

tf.multiply(a, b)

Create a variable tensor

Create a variable

object

randomized value

tf.get_variable("var", [1, 2])

initialized first value

tf.get_variable("var_init_2", dtype=tf.int32, initializer=[ [1, 2], [3, 4] ])

Open a session

Session

object

Create a session

tf.Session()

Run a session

tf.Session.run()

Evaluate a tensor

variable_name.eval()

Close a session

sess.close()

Session by block

with tf.Session() as sess:

 