# Numpy - Numerical python

In [2]:
# Numpy array is homogeneous

import numpy as np

a = np.array([4.5, 5, 6, 'data'])
a

array(['4.5', '5', '6', 'data'], dtype='<U32')

In [3]:
c = np.array(['abcd', '5', 6])
c

array(['abcd', '5', '6'], dtype='<U4')

In [4]:
a = np.array([4, 5, 6, 8])
print(a)
print('size of array: ', a.size)
print('datatype of the array', a.dtype)
print('Dimension of the array', a.ndim)
print('Shape of the array', a.shape)

print('type of the array', type(a))

[4 5 6 8]
size of array:  4
datatype of the array int32
Dimension of the array 1
Shape of the array (4,)
type of the array <class 'numpy.ndarray'>


2d array is a collection of one dimensional array

In [5]:
a = np.array([[4, 5, 6, 8], [8, 4, 26, 18], [8, 52, 16, 22] ])
print(a)
print('size of array: ', a.size)
print('datatype of the array', a.dtype)
print('Dimension of the array', a.ndim)
print('Shape of the array', a.shape)

print('type of the array', type(a))

[[ 4  5  6  8]
 [ 8  4 26 18]
 [ 8 52 16 22]]
size of array:  12
datatype of the array int32
Dimension of the array 2
Shape of the array (3, 4)
type of the array <class 'numpy.ndarray'>


collection of one dimensional arrays
Dont think about this as rows and columns
Rows and columns are in pandas.
Do not get confused

In [6]:
a = np.array([[4, 5, 6, 8], [5]])
print(a)
print('size of array: ', a.size)
print('datatype of the array', a.dtype)
print('Dimension of the array', a.ndim)
print('Shape of the array', a.shape)

print('type of the array', type(a))

[list([4, 5, 6, 8]) list([5])]
size of array:  2
datatype of the array object
Dimension of the array 1
Shape of the array (2,)
type of the array <class 'numpy.ndarray'>


In the above case it is not a 2 d array anymore
because one of the lists contains only 1 element.

It becomes a 1 dimensional array with 1 object

3 dimensional array is a collection of 2 d array and so on


In [7]:
a = np.array([
    
   [ [4, 5, 6, 8], [8, 4, 26, 18], [8, 52, 16, 22] ],

   [  [4, 5, 6, 8], [8, 4, 26, 18], [8, 52, 16, 22] ]


])
print(a)
print('size of array: ', a.size)
print('datatype of the array', a.dtype)
print('Dimension of the array', a.ndim)
print('Shape of the array', a.shape)

print('type of the array', type(a))

[[[ 4  5  6  8]
  [ 8  4 26 18]
  [ 8 52 16 22]]

 [[ 4  5  6  8]
  [ 8  4 26 18]
  [ 8 52 16 22]]]
size of array:  24
datatype of the array int32
Dimension of the array 3
Shape of the array (2, 3, 4)
type of the array <class 'numpy.ndarray'>


In [8]:
a[1]

array([[ 4,  5,  6,  8],
       [ 8,  4, 26, 18],
       [ 8, 52, 16, 22]])

In [9]:
a[1][0]

array([4, 5, 6, 8])

In [10]:
a[1][0][0]

4

In [11]:
a[1,0,0]

4

Any kind of data used for artificial intelligence finally ends up in numpy in python

April fool joke of communicating with plants by google



In [12]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(np.arange(10, 20))

[10 11 12 13 14 15 16 17 18 19]


starting position is included, excludes the end position

In [14]:
print(np.arange(10, 20, 2))

[10 12 14 16 18]


# np.linspace() Linear space

In [15]:
np.linspace(10, 50, 3)

array([10., 30., 50.])

give me 41 numbers equally spaced between 10 and 50 including both numbers

linspace is useful to generate sample space



In [16]:
np.linspace(10, 50, 41)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49., 50.])

In [17]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
b = np.arange(24).reshape(4, 6) # . is also used for piping
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [19]:
b.shape

(4, 6)

In [20]:
b.reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
c = b.reshape(1,3,2,2,2)
c

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]],


        [[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]]]])

In [22]:
c.shape

(1, 3, 2, 2, 2)

In [23]:
d = b.reshape(2, 2, 2, 3, 1, 1)
d

array([[[[[[ 0]],

          [[ 1]],

          [[ 2]]],


         [[[ 3]],

          [[ 4]],

          [[ 5]]]],



        [[[[ 6]],

          [[ 7]],

          [[ 8]]],


         [[[ 9]],

          [[10]],

          [[11]]]]],




       [[[[[12]],

          [[13]],

          [[14]]],


         [[[15]],

          [[16]],

          [[17]]]],



        [[[[18]],

          [[19]],

          [[20]]],


         [[[21]],

          [[22]],

          [[23]]]]]])

In [24]:
d.shape

(2, 2, 2, 3, 1, 1)

In practice we play with one or two dimensions

In [25]:
# ravel flatten an array back to single dimension

In [26]:

d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# np.random.rand()
random subpackage


In [27]:
# 16 digit decimal precision number between 0 and 1
np.random.rand()

0.6900588159194561

In [28]:
np.random.rand() * 100

60.382304337264195

In [29]:
# number between 35 and 100
# min + rand() * (max - min)
35 + int(np.random.rand() * 65) 

68

In [30]:
def random_between(min_value, max_value):
    """ A fuction which returns an integer between min_value and max_value
    """
    return min_value + int(np.random.rand() * (max_value - min_value))

random_between(65, 70)

69

In [31]:
# 5 ranodm numbers between 0 and 1
np.random.rand(5)

array([0.46444571, 0.0279086 , 0.58804388, 0.9331591 , 0.93958228])

In [32]:
# 3 x 4 2d array
# takes any shape and gives a random array of that shape
np.random.rand(3, 4)

array([[0.72349061, 0.59637706, 0.55353876, 0.38033911],
       [0.73946222, 0.0254033 , 0.14922482, 0.11546467],
       [0.14697336, 0.21405767, 0.83072286, 0.61804003]])

In [33]:
# randint
# what we wrote above
np.random.randint(35, 100)

71

In [34]:
# 100 numbers between 35 and 100
np.random.randint(35, 100 ,100)

array([77, 85, 47, 64, 41, 40, 49, 52, 76, 47, 91, 67, 62, 43, 94, 38, 80,
       86, 46, 78, 53, 92, 62, 48, 91, 37, 91, 39, 77, 78, 86, 87, 40, 57,
       62, 72, 81, 75, 79, 88, 79, 93, 71, 73, 80, 49, 57, 50, 89, 54, 78,
       72, 88, 68, 65, 94, 88, 54, 57, 94, 62, 78, 45, 67, 92, 49, 75, 79,
       87, 36, 78, 58, 58, 73, 47, 74, 97, 40, 68, 59, 46, 40, 39, 96, 63,
       57, 82, 54, 41, 61, 42, 46, 53, 66, 71, 86, 54, 61, 61, 98])

In [35]:
np.random.randint(35, 100, 100).reshape(20, 5)

array([[41, 49, 38, 76, 72],
       [82, 96, 53, 90, 98],
       [86, 69, 78, 65, 75],
       [55, 54, 38, 67, 84],
       [85, 87, 73, 90, 68],
       [87, 47, 75, 80, 93],
       [82, 47, 56, 90, 60],
       [36, 93, 56, 44, 76],
       [72, 93, 37, 62, 59],
       [71, 89, 50, 84, 59],
       [38, 39, 93, 52, 37],
       [35, 87, 87, 76, 53],
       [48, 94, 86, 47, 77],
       [72, 76, 37, 43, 53],
       [85, 40, 96, 61, 94],
       [66, 82, 38, 73, 71],
       [95, 80, 76, 84, 88],
       [82, 69, 54, 94, 76],
       [76, 54, 95, 97, 64],
       [97, 56, 98, 98, 37]])

In [36]:
# numpy is very efficient
np.sqrt(np.random.randint(35, 100, int(1e6)).reshape(int(1e3), 1000))

array([[7.41619849, 8.54400375, 7.74596669, ..., 8.24621125, 9.79795897,
        7.81024968],
       [9.32737905, 6.63324958, 7.        , ..., 8.36660027, 9.2736185 ,
        6.164414  ],
       [9.38083152, 9.38083152, 8.06225775, ..., 9.48683298, 8.71779789,
        8.94427191],
       ...,
       [8.77496439, 9.69535971, 6.40312424, ..., 6.164414  , 8.36660027,
        8.88819442],
       [7.61577311, 9.43398113, 8.77496439, ..., 8.06225775, 7.28010989,
        8.        ],
       [8.06225775, 8.        , 9.21954446, ..., 7.07106781, 8.48528137,
        9.11043358]])

In [37]:
np.log(np.pi)

1.1447298858494002

In [38]:
 a = np.arange(24).reshape(4, 6)

In [39]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [40]:
np.hsplit(a, 2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [41]:
np.vsplit(a, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [42]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [43]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [44]:
np.hstack((a, b))

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23]])

In [45]:
np.vstack((a, b))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [46]:
a = [4, 5, 6]

b = a

print(a, b)

a[1] = 500

print(a, b)

[4, 5, 6] [4, 5, 6]
[4, 500, 6] [4, 500, 6]


In [47]:
a = [4, 5, 6]

b = a.copy() # deep copy

print(a, b)

a[1] = 500

print(a, b)

[4, 5, 6] [4, 5, 6]
[4, 500, 6] [4, 5, 6]
