In [18]:
import torch

In [19]:
def addr(x, y):
    return x + y

addr(torch.zeros(5), torch.ones(5))

tensor([1., 1., 1., 1., 1.])

exponential shows significant difference

exp(12.1) and exp(12.3) can be different significantly 
square may not do this difference

mx+c

exp(mx+c) non negative

n

n / (n+1) always less than 1

sigmoid function less than 1


In [20]:
def sigmoid(x):
    return torch.exp(x) / (1+torch.exp(x))

In [21]:
torch.manual_seed(7) # random state

In [22]:
torch.randn_like(torch.ones(5))

tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908])

In [23]:
X = torch.randn((1, 3))
weights = torch.randn((3, 1))
torch.matmul(X, weights)

tensor([[0.8661]])

In [24]:
bias = torch.tensor([[1]])

In [25]:
torch.matmul(X, weights)

tensor([[0.8661]])

In [26]:
torch.matmul(X, weights) + bias

tensor([[1.8661]])

In [27]:
sigmoid(torch.matmul(X, weights))

tensor([[0.7039]])

In [28]:
sigmoid(torch.matmul(X, weights) + bias)

tensor([[0.8660]])

In [29]:
features = torch.randn(1, 3)

In [30]:
features

tensor([[0.1328, 0.1373, 0.2405]])

In [ ]:
n_input = 3
n_hidden = 4
n_output = 1

In [31]:
weights_1 = torch.randn(3, 1)

In [32]:
weights_1

tensor([[1.3955],
        [1.3470],
        [2.4382]])

In [41]:
weights_2 = torch.randn(4, 1)

In [36]:
b1 = torch.randn(4, 1)

In [37]:
b2 = torch.randn(1, 1)

In [43]:
weights_2

tensor([[-0.7245],
        [ 1.2799],
        [-0.9941],
        [ 1.8150]])

In [44]:
torch.mm(features, weights_1)

tensor([[0.9568]])

In [39]:
h = sigmoid(torch.mm(features, weights_1) + b1)

In [45]:
sigmoid(torch.mm(weights_2, h) + b2)

RuntimeError: size mismatch, m1: [4 x 1], m2: [4 x 1] at C:\cb\pytorch_1000000000000\work\aten\src\TH/generic/THTensorMath.cpp:41