In [1]:
import torch

In [4]:
def mult (x,y):
    return x*y

In [5]:
mult(5,3)

15

In [ ]:
# Sigmoid activation function

In [6]:
def sigmoid(x):
    return torch.exp(x)/(1+torch.exp(x))
    

In [7]:
w = torch.Tensor([3])

In [8]:
type(w)

torch.Tensor

In [9]:
sigmoid(w)

tensor([0.9526])

# Simple neural network

<img src="Simple Neuaral network.gif" align="center" width=350, height=350>

In [10]:
torch.manual_seed(7)

In [11]:
X = torch.randn((1,3))

In [12]:
X

tensor([[-0.1468,  0.7861,  0.9468]])

In [13]:
X.shape

torch.Size([1, 3])

In [14]:
weights = torch.randn_like(X)

In [15]:
weights

tensor([[-1.1143,  1.6908, -0.8948]])

In [16]:
bias = torch.randn(X.shape[0])

In [17]:
bias

tensor([-0.3556])

In [ ]:
#weight * input(x)

In [20]:
weights.shape

torch.Size([1, 3])

In [18]:
torch.matmul(X,weights)

RuntimeError: size mismatch, m1: [1 x 3], m2: [1 x 3] at ..\aten\src\TH/generic/THTensorMath.cpp:961

In [21]:
weights_reshape = weights.view(3,-1)

In [22]:
weights_reshape.shape

torch.Size([3, 1])

In [23]:
torch.matmul(X,weights_reshape)

tensor([[0.6455]])

In [25]:
sigmoid(torch.matmul(X,weights_reshape)+bias)

tensor([[0.5720]])

# Multi layer neural network

<img src="1 Hidden layer NN.png" width=250, height=250>

In [26]:
features = torch.randn((1,3))

In [27]:
features

tensor([[ 1.2324,  0.1382, -1.6822]])

In [ ]:
# neurons
n_input = 3
n_hidden = 4
n_output = 1

In [28]:
weights1 = torch.randn(3,4)

In [29]:
weights1

tensor([[ 0.3177,  0.1328,  0.1373,  0.2405],
        [ 1.3955,  1.3470,  2.4382,  0.2028],
        [ 2.4505,  2.0256,  1.7792, -0.9179]])

In [30]:
weights2 = torch.randn(4,1)

In [31]:
weights2

tensor([[-0.4578],
        [-0.7245],
        [ 1.2799],
        [-0.9941]])

In [32]:
b1 = torch.randn(1,4)

In [33]:
b1

tensor([[ 1.8150, -0.6028,  1.6148,  1.9302]])

In [34]:
b2 = torch.randn(1,1)

In [35]:
b2

tensor([[-0.4225]])

In [37]:
torch.mm(features,weights1)+b1

tensor([[-1.7230, -3.6605, -0.8719,  3.7988]])

In [40]:
h = sigmoid(torch.mm(features,weights1)+b1)

In [41]:
h

tensor([[0.1515, 0.0251, 0.2948, 0.9781]])

In [43]:
torch.mm(h,weights2)+b2


tensor([[-1.1049]])

In [44]:
sigmoid(torch.mm(h,weights2)+b2)

tensor([[0.2488]])

In [ ]:
output

In [ ]:
# Sample code for ANN in pytorch

In [ ]:
class Conv(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(784,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,1)
        
    def forward(self,x):

        x = F.relu(self.fc1(x))
        x = F.softmax(self.fc2(x))
        x = F.signoid(x)
        
        return x