In [1]:
import torch
import numpy as np

In [2]:
import torch

In [3]:
w =torch.zeros(5)

In [4]:
w

tensor([0., 0., 0., 0., 0.])

In [5]:
type(w)

torch.Tensor

In [6]:
r =np.zeros(5)

In [7]:
r

array([0., 0., 0., 0., 0.])

In [8]:
type(r)

numpy.ndarray

In [9]:
type(w)

torch.Tensor

In [10]:
f = torch.tensor([[1.0, 2.0],[3.0, 4.0]])

In [11]:
f

tensor([[1., 2.],
        [3., 4.]])

In [12]:
f.shape

torch.Size([2, 2])

In [13]:
type(f)

torch.Tensor

In [14]:
y =torch.rand((5,3))

In [15]:
y

tensor([[0.9907, 0.8084, 0.4776],
        [0.2143, 0.7835, 0.4547],
        [0.6231, 0.1371, 0.5553],
        [0.9441, 0.4185, 0.6169],
        [0.9794, 0.4861, 0.5986]])

In [16]:
y.shape

torch.Size([5, 3])

In [17]:
X = np.random.random((5, 3))

In [18]:
X.shape

(5, 3)

In [19]:
type(X)

numpy.ndarray

In [20]:
X


array([[0.44413868, 0.80715307, 0.19303189],
       [0.27412119, 0.74151581, 0.93370646],
       [0.57254119, 0.04714543, 0.18230348],
       [0.16416319, 0.75990991, 0.2212804 ],
       [0.39517164, 0.4262367 , 0.99506616]])

In [21]:
torch.arange(2,10,2)

tensor([2, 4, 6, 8])

In [22]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [23]:
X = torch.rand(3, 2)

In [24]:
X

tensor([[0.1446, 0.3799],
        [0.2745, 0.2053],
        [0.6947, 0.7961]])

In [25]:
torch.exp(X)

tensor([[1.1555, 1.4622],
        [1.3158, 1.2278],
        [2.0031, 2.2168]])

In [26]:
X.exp()

tensor([[1.1555, 1.4622],
        [1.3158, 1.2278],
        [2.0031, 2.2168]])

In [27]:
X.sqrt()

tensor([[0.3802, 0.6164],
        [0.5239, 0.4531],
        [0.8335, 0.8922]])

In [28]:
B=torch.eye(3)

In [29]:
B

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [30]:
type(B)

torch.Tensor

In [31]:
B.add(5)

tensor([[6., 5., 5.],
        [5., 6., 5.],
        [5., 5., 6.]])

In [32]:
A = torch.randint( 0,100, (3, 3))
A

tensor([[60, 22, 43],
        [43, 94,  7],
        [17, 49, 85]])

In [33]:
A[1,1]

tensor(94)

In [34]:
A[:,1]

tensor([22, 94, 49])

In [35]:
A[1,:]

tensor([43, 94,  7])

In [36]:
A[:2, :2]

tensor([[60, 22],
        [43, 94]])

In [37]:
A[1:, 1:]

tensor([[94,  7],
        [49, 85]])

In [38]:
X = torch.tensor([1, 2, 3, 4])
X

tensor([1, 2, 3, 4])

In [39]:
X = X.repeat(3, 1) # repeat it 3 times along 0th dimension and 1 times along first dimension
X, X.shape

(tensor([[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]), torch.Size([3, 4]))

In [40]:
Y = X.view(2, 6)

In [41]:
Y

tensor([[1, 2, 3, 4, 1, 2],
        [3, 4, 1, 2, 3, 4]])

Matrix Multiplication

In [42]:
x1 = torch.tensor([[3,4],[2,1]])

In [43]:
x1

tensor([[3, 4],
        [2, 1]])

In [44]:
x1.shape

torch.Size([2, 2])

In [45]:
x2 = torch.tensor([[1,5],[3,7]])

In [46]:
x2

tensor([[1, 5],
        [3, 7]])

In [47]:
x2.shape

torch.Size([2, 2])

In [48]:
torch.mm(x1,x2)

tensor([[15, 43],
        [ 5, 17]])

Dimensions must be (m,n)*(n,k)

Resulting dimension (m,k)

In [49]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [50]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [51]:
a.shape

torch.Size([2, 3])

In [52]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [53]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [54]:
b.shape

torch.Size([3, 2])

In [55]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [56]:
torch.manual_seed(12)

In [57]:
w1 = torch.eye(3)

In [58]:
torch.exp(w1)

tensor([[2.7183, 1.0000, 1.0000],
        [1.0000, 2.7183, 1.0000],
        [1.0000, 1.0000, 2.7183]])

In [59]:
w1

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [60]:
w2 = torch.eye(3)

In [61]:
torch.exp_(w2)

tensor([[2.7183, 1.0000, 1.0000],
        [1.0000, 2.7183, 1.0000],
        [1.0000, 1.0000, 2.7183]])

In [62]:
w2

tensor([[2.7183, 1.0000, 1.0000],
        [1.0000, 2.7183, 1.0000],
        [1.0000, 1.0000, 2.7183]])